# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
  - PROJECT_DIR="$PWD"
  - echo $PROJECT_DIR
  - mkdir upload

script:
  # Download and build Python
  - cd "$PROJECT_DIR"
  - sh build_python.sh

  # Compress and upload it before touching it
  - cd "$PROJECT_DIR"
  - zip --symlinks -r upload/python3-only.zip python-portable/ 1> /dev/null
  - curl --upload-file ./upload/python3-only.zip https://transfer.sh/python3-only.zip | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Check built Python
  - cd "$PROJECT_DIR"
  - du -sk python-portable/
  - cd python-portable
  - otool -L bin/python3.6
  - ./bin/python3.6 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
  - ./bin/python3.6 -m pip --version

  # Reduce stand-alone Python and upload it
  - cd "$PROJECT_DIR"
  - python process_python_build.py "$PROJECT_DIR/python-portable"
  - zip --symlinks -r upload/python3-only-reduced.zip python-portable/ 1> /dev/null
  - curl --upload-file ./upload/python3-only-reduced.zip https://transfer.sh/python3-only-reduced.zip | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Install Mu
  - cd "$PROJECT_DIR"
  - git clone https://github.com/mu-editor/mu.git
  - cd mu
  - "./$PROJECT_DIR/python-portable/bin/python3.6" -m pip install .

  # Process Python build with Mu into an App Bundle
  - cd "$PROJECT_DIR"
  - python process_python_build.py "$PROJECT_DIR/python-portable"

  # Create an App Bundle and zipped version to upload
  - cd "$PROJECT_DIR"
  - python create_app_bundle.py "$PROJECT_DIR/python-portable" "Mu"
  - mv "$PROJECT_DIR/mu-portable.zip" "$PROJECT_DIR/upload/mu-portable.zip"
  - curl --upload-file ./upload/mu-portable.zip https://transfer.sh/mu-portable.zip | tee -a output_urls.txt && echo "" >> output_urls.txt
  
  # Create a DMG package and upload it
  - cd "$PROJECT_DIR"
  - git clone https://github.com/andreyvit/yoursway-create-dmg.git
  - cd yoursway-create-dmg
  # TODO: Create background and add it with "--background "installer_background.png""
  - |
    ./create-dmg \
    --volname "Mu Installer" \
    --volicon "$PROJECT_DIR/app_bundle/appIcon.icns" \
    --window-pos 200 120 \
    --window-size 800 400 \
    --icon-size 100 \
    --icon Application.app 200 190 \
    --hide-extension Mu.app \
    --app-drop-link 600 185 \
    "$PROJECT_DIR/upload/Mu-Installer.dmg" \
    "$PROJECT_DIR/Mu.app/"
  - curl --upload-file "$PROJECT_DIR/upload/Mu-Installer.dmg" https://transfer.sh/Mu-Installer.dmg | tee -a output_urls.txt

  # Print all uploaded files URLs
  - cd "$PROJECT_DIR"
  - cat output_urls.txt
