# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
  - PROJECT_DIR="$PWD"
  - echo $PROJECT_DIR

script:
  # Download and build Python
  - sh build_python.sh

  # Check built Python
  - cd "$PROJECT_DIR"
  - du -sk python-portable/
  - cd python-portable
  - otool -L bin/python3.6
  - ./bin/python3.6 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
  - ./bin/python3.6 -m pip --version

  # Process Python build (removes unnecessary stuff)
  - cd "$PROJECT_DIR"
  - python process_python_build.py "$PROJECT_DIR/python-portable"

  # Compress and upload it
  - cd "$PROJECT_DIR"
  - mkdir upload
  - zip --symlinks -r upload/python3.6-only.zip Python-portable/ 1> /dev/null
  - curl --upload-file ./upload/python3.6-only.zip https://transfer.sh/python3.6-only.zip

  # Install Mu
  - cd "$PROJECT_DIR/python-portable"
  - ./bin/python3.6 -m pip install mu-editor

  # Process Python build again now that Mu and dependencies were added
  - cd "$PROJECT_DIR"
  - python process_python_build.py "$PROJECT_DIR/python-portable"

  # Create an App Bundle for the application
  - python create_app_bundle.py "$PROJECT_DIR/python-portable" "Mu"

  # Compress and upload it
  - cd "$PROJECT_DIR"
  - zip --symlinks -r upload/mu-portable.zip python-portable/ 1> /dev/null
  - curl --upload-file ./upload/mu-portable.zip https://transfer.sh/mu-portable.zip
